### ISSUE TITLE
Query on FormIO Grid

### ISSUE THREAD

**Issue by A-Pradeep** [formio/angular-app-starterkit#14]
@travist  , Hi , i'm trying to add the Data Table / formio-grid. as per the [documentation](https://github.com/formio/angular-formio/wiki/Data-Table)  provided. As per the doc , ive tried and end up in the error as `Template parse errors:
Can't bind to 'formio' since it isn't a known property of 'formio-grid'.`   
or the error as below 

![image](https://user-images.githubusercontent.com/37439293/51466854-259cb080-1d91-11e9-9ec2-4aead437893b.png)

Am i missing out any steps ?

_Originally posted by @A-Pradeep in https://github.com/formio/angular-app-starterkit/issues/13#issuecomment-456015561_

I'm still facing the same error.  And the [documentation](https://github.com/formio/angular-formio/wiki/Data-Table) has not updated yet.  How  Can i solve the problem  & show something like this !  https://github.com/formio/formio-app-formio/blob/master/src/assets/images/form-manager-preview.png

**Comment by travist** [comment]
You just need to include the ```FormioModule``` in your module that is including the FormioGrid component since it also depends on FormioModule.
