### ISSUE TITLE
[BUG]  Latest version of Form.io + Angular-formio causes Zone.js error

### ISSUE THREAD

**Issue by bh-adrienne** [formio/angular-app-starterkit#17]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.3.13
- Frontend framework: Angular
- Browser:
- Browser version:

## Steps to Reproduce
1.  Check out this repository.  Run 'npm install'. 
2. Navigate to localhost:4200 

## Expected behavior
App should load. 

## Observed behavior
App does not load due to console error:

Error: "Zone.js has detected that ZoneAwarePromise (window|global).Promise has been overwritten. Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)" 
Angular 5 notify es.promise.js:114 flush microtask.js:26 Angular 3

<img width="1280" alt="Screen Shot 2019-12-27 at 5 27 27 PM" src="https://user-images.githubusercontent.com/44947170/71534659-3c675380-28ce-11ea-887d-63985b75e563.png">

**Comment by travist** [comment]
I will take a look at this today or tomorrow. It will be a high priority to fix it.

**Comment by travist** [comment]
This is fixed with latest version.
