### ISSUE TITLE
Arrow functions in routes

### ISSUE THREAD

**Issue by datnav** [formio/angular-app-starterkit#6]
A production build ( `ng build --prod` ) produces the following error:

> ERROR in Error during template compile of 'AppModule'
  Function expressions are not supported in decorators in 'ɵ0'
    'ɵ0' contains the error at src/app/app.module.ts(40,23)
      Consider changing the function expression into an exported function.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
