### ISSUE TITLE
Parent field not hidden on page refresh

### ISSUE THREAD

**Issue by steph-lebl** [formio/angular-app-starterkit#8]
Repro:
- Follow the instructions to setup the Angular Starter Application
https://github.com/formio/angular-app-starterkit
- Follow the link to create a new participant for an event
- Refresh the page (F5)
- Bug: The event field is not hidden anymore.

Note: This bug also occurs in edit mode. This is very problematic for us, since users will share hyperlinks via mail.

Hint1: At first I suspected that the problem was caused because of the dynamic nested form, but the problem can be reproduced without the nested form. 
Hint2: From my analysis, the root cause of the problem seems to be in https://github.com/formio/angular-formio.

Note: I am able to reproduce the problem with the latest alpha version(69651e70fe16d1bb915c8efc0a6528d57d75aaed) and with the latest stable version(70f54d4d23b4efa3e726d9c7e777eeeaf4b9584b). It would be nice if the latest stable version could be tagged on the git history.

![parent-field-not-hidden-on-page-refresh](https://user-images.githubusercontent.com/8179295/40625456-9db2c680-6280-11e8-8041-5249ac99a781.png)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
